---
#Tasks to terminate EC2 instance
- name: STOP EC2 instance
  hosts: localhost
  connection: local
  gather_facts: False

  vars:
      region: us-west-2
      instance_type: t2.micro
      ami: ami-01e24be29428c15b2
      keypair: basic-key

  tasks:
    - name: stopping ec2 instance
      ec2:
        region:  "{{ region }}"
        aws_access_key: ""
        aws_secret_key: ""
        state: "absent"
        instance_ids: "i-0062a9ea445804efe"
        wait: yes




