---
# tasks file for jenkins_inst

- name: Create Jenkins directory
  file:
      state: directory
      owner: root
      group: root
      path: /opt/jenkins-ansible

- name: Install pip
  easy_install:
    name: pip
    state: latest

- name: Install docker-py
  pip:
    name: docker-py  

- name: Create a container from the jenkins docker image
  docker_container:
      name: jenkins-ansible
      image: jenkinsci/blueocean
      user: root
      state: started
      recreate: no
      ports:
        - "8672:8080"
        - "50001:50001"
      volumes:
        - "/opt/jenkins-ansible:/var/jenkins_home"
        - "/var/run/docker.sock:/var/run/docker.sock"






































